dolibarr:
  image: tuxgasy/dolibarr:20.0.2
  replicas: 1
  adminLogin: "admin"
  adminPassword: ""
  modules: ""
  phpMemoryLimit: "256M"
  uploadMaxSize: "64M"
  timezone: "UTC"
  storageSize: 15Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

mariadb:
  image: mariadb:11.8
  rootPassword: ""
  database: dolibarr
  user: doli_user
  password: ""
  storageSize: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"

dolibarrCustom:
  storageSize: 1Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
