apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-config
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
data:
  MOODLE_DATABASE_HOST: {{ include "moodle-bitnami.fullname" . }}-mariadb
  MOODLE_DATABASE_NAME: {{ .Values.mariadb.database | quote }}
  MOODLE_DATABASE_USER: {{ .Values.mariadb.user | quote }}
  MOODLE_SITE_NAME: {{ .Values.moodle.siteName | quote }}
  MOODLE_LANG: {{ .Values.moodle.lang | quote }}
  PHP_MEMORY_LIMIT: {{ .Values.moodle.phpMemoryLimit | quote }}
  PHP_MAX_UPLOAD_SIZE: {{ .Values.moodle.phpMaxUploadSize | quote }}
  BITNAMI_DEBUG: "false"
  MOODLE_SSLPROXY: "true"
  MOODLE_HOST: {{ .Values.ingress.domain | quote }}
