apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-cron
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
    app.kubernetes.io/component: moodle-cron
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "moodle-bitnami.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: moodle-cron
        spec:
          restartPolicy: Never
          securityContext:
            fsGroup: 1001
          containers:
            - name: moodle-cron
              image: {{ .Values.moodle.image }}
              command:
                - php
                - /bitnami/moodle/admin/cli/cron.php
              envFrom:
                - secretRef:
                    name: {{ include "moodle-bitnami.fullname" . }}-secret
                - configMapRef:
                    name: {{ include "moodle-bitnami.fullname" . }}-config
              volumeMounts:
                - name: moodle-data
                  mountPath: /bitnami/moodle
                - name: moodledata
                  mountPath: /bitnami/moodledata
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              securityContext:
                runAsUser: 1001
                runAsNonRoot: true
          volumes:
            - name: moodle-data
              persistentVolumeClaim:
                claimName: {{ include "moodle-bitnami.fullname" . }}-moodle-data
            - name: moodledata
              persistentVolumeClaim:
                claimName: {{ include "moodle-bitnami.fullname" . }}-moodledata
