apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
    app.kubernetes.io/component: moodle
spec:
  replicas: {{ .Values.moodle.replicas }}
  selector:
    matchLabels:
      {{- include "moodle-bitnami.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: moodle
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "moodle-bitnami.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: moodle
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: moodle
          image: {{ .Values.moodle.image }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "moodle-bitnami.fullname" . }}-secret
            - configMapRef:
                name: {{ include "moodle-bitnami.fullname" . }}-config
          volumeMounts:
            - name: moodle-data
              mountPath: /bitnami/moodle
            - name: moodledata
              mountPath: /bitnami/moodledata
          resources:
            requests:
              cpu: {{ .Values.moodle.resources.requests.cpu }}
              memory: {{ .Values.moodle.resources.requests.memory }}
            limits:
              cpu: {{ .Values.moodle.resources.limits.cpu }}
              memory: {{ .Values.moodle.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /login/index.php
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /login/index.php
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
      volumes:
        - name: moodle-data
          persistentVolumeClaim:
            claimName: {{ include "moodle-bitnami.fullname" . }}-moodle-data
        - name: moodledata
          persistentVolumeClaim:
            claimName: {{ include "moodle-bitnami.fullname" . }}-moodledata
