apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-moodle
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "moodle-bitnami.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: moodle
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-mariadb
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "moodle-bitnami.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "moodle-bitnami.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: moodle
      ports:
        - port: 3306
          protocol: TCP
{{- if .Values.redis.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-redis
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "moodle-bitnami.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "moodle-bitnami.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: moodle
      ports:
        - port: 6379
          protocol: TCP
{{- end }}
