apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-moodle-data
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
    app.kubernetes.io/component: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.moodle.dataStorageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-moodledata
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
    app.kubernetes.io/component: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.moodle.dataStorageSize }}
