apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moodle-bitnami.fullname" . }}-secret
  labels:
    {{- include "moodle-bitnami.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  MOODLE_DATABASE_PASSWORD: {{ .Values.mariadb.password | quote }}
  MOODLE_USERNAME: {{ .Values.moodle.username | quote }}
  MOODLE_PASSWORD: {{ .Values.moodle.password | quote }}
  MOODLE_EMAIL: {{ .Values.moodle.email | quote }}
  {{- if .Values.moodle.smtpHost }}
  MOODLE_SMTP_HOST: {{ .Values.moodle.smtpHost | quote }}
  MOODLE_SMTP_PORT_NUMBER: {{ .Values.moodle.smtpPort | quote }}
  MOODLE_SMTP_USER: {{ .Values.moodle.smtpUser | quote }}
  MOODLE_SMTP_PASSWORD: {{ .Values.moodle.smtpPassword | quote }}
  {{- end }}
