apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.fullname" . }}-vw-data
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vwData.storageSize }}
