apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-secret
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken | quote }}
  SIGNUPS_ALLOWED: {{ .Values.vaultwarden.signupsAllowed | quote }}
  DOMAIN: "https://{{ .Values.ingress.domain }}"
  {{- if .Values.smtp.host }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  SMTP_SECURITY: "starttls"
  {{- end }}
