{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "wordpress.fullname" . }}-cron
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: wp-cron
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "wordpress.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: wp-cron
        spec:
          restartPolicy: Never
          containers:
            - name: wp-cron
              image: curlimages/curl:latest
              command:
                - curl
                - -fsS
                - "http://{{ include "wordpress.fullname" . }}:80/wp-cron.php?doing_wp_cron"
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 50m
                  memory: 32Mi
{{- end }}
