apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}-wp-content
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wpContent.storageSize }}
