apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  WORDPRESS_DB_HOST: {{ include "wordpress.fullname" . }}-mariadb
  WORDPRESS_DB_NAME: {{ .Values.mariadb.database | quote }}
  WORDPRESS_DB_USER: {{ .Values.mariadb.user | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mariadb.password | quote }}
  WORDPRESS_ADMIN_USER: {{ .Values.wordpress.adminUser | quote }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.wordpress.adminPassword | quote }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.wordpress.adminEmail | quote }}
  {{- if .Values.smtp.host }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  {{- end }}
