apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wordpress.fullname" . }}-mariadb
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  serviceName: {{ include "wordpress.fullname" . }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "wordpress.fullname" . }}-secret
          resources:
            requests:
              cpu: {{ .Values.mariadb.resources.requests.cpu }}
              memory: {{ .Values.mariadb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mariadb.resources.limits.cpu }}
              memory: {{ .Values.mariadb.resources.limits.memory }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
                - --innodb_initialized
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - healthcheck.sh
                - --connect
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mariadb.storageSize }}
