replicaCount: 1

image:
  repository: memcached
  tag: "1.6-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11211

resources:
  requests:
    cpu: 0.10
    memory: 128Mi
  limits:
    cpu: 0.10
    memory: 128Mi

persistence:
  enabled: false
