apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "strapi.fullname" . }}-strapi-data
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: strapi
spec:
  accessModes:
    - {{ .Values.persistence.strapiData.accessMode }}
  {{- if .Values.persistence.strapiData.storageClass }}
  storageClassName: {{ .Values.persistence.strapiData.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.strapiData.size }}
