apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi.fullname" . }}-secret
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  admin-jwt-secret: {{ .Values.admin.jwtSecret | quote }}
  app-keys: {{ .Values.app.keys | quote }}
  api-token-salt: {{ .Values.app.apiTokenSalt | quote }}
  transfer-token-salt: {{ .Values.app.transferTokenSalt | quote }}
