apiVersion: v1
kind: Service
metadata:
  name: {{ include "strapi.fullname" . }}-app
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: strapi
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.strapi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "strapi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: strapi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strapi.fullname" . }}-postgresql
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "strapi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
