apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
    app.kubernetes.io/component: matomo
spec:
  replicas: {{ .Values.matomo.replicas }}
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: matomo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "matomo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: matomo
    spec:
      containers:
        - name: matomo
          image: {{ .Values.matomo.image }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "matomo.fullname" . }}-secret
          volumeMounts:
            - name: matomo-data
              mountPath: /var/www/html
          resources:
            requests:
              cpu: {{ .Values.matomo.resources.requests.cpu }}
              memory: {{ .Values.matomo.resources.requests.memory }}
            limits:
              cpu: {{ .Values.matomo.resources.limits.cpu }}
              memory: {{ .Values.matomo.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /matomo.php
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /matomo.php
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: false
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: {{ include "matomo.fullname" . }}-matomo-data
