apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matomo.fullname" . }}-matomo-data
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
    app.kubernetes.io/component: matomo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.matomoData.storageSize }}
