apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}-secret
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  MATOMO_DATABASE_HOST: {{ include "matomo.fullname" . }}-mariadb
  MATOMO_DATABASE_DBNAME: {{ .Values.mariadb.database | quote }}
  MATOMO_DATABASE_USERNAME: {{ .Values.mariadb.user | quote }}
  MATOMO_DATABASE_PASSWORD: {{ .Values.mariadb.password | quote }}
  MATOMO_DATABASE_ADAPTER: "MYSQLI"
  MATOMO_GENERAL_ADMIN_USER: {{ .Values.matomo.adminUser | quote }}
  MATOMO_GENERAL_ADMIN_PASSWORD: {{ .Values.matomo.adminPassword | quote }}
  {{- if .Values.smtp.host }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  {{- end }}
