apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-data
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
    app.kubernetes.io/component: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kumaData.storageSize }}
