apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}
    app.kubernetes.io/component: uptime-kuma
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "uptime-kuma.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: uptime-kuma
