apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.postgresql.password | quote }}
  N8N_BASIC_AUTH_USER: {{ .Values.n8n.basicAuthUser | quote }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.basicAuthPassword | quote }}
  N8N_ENCRYPTION_KEY: {{ .Values.n8n.encryptionKey | quote }}
  {{- if .Values.smtp.host }}
  N8N_EMAIL_MODE: "smtp"
  N8N_SMTP_HOST: {{ .Values.smtp.host | quote }}
  N8N_SMTP_PORT: {{ .Values.smtp.port | quote }}
  N8N_SMTP_USER: {{ .Values.smtp.username | quote }}
  N8N_SMTP_PASS: {{ .Values.smtp.password | quote }}
  {{- end }}
