apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discourse.fullname" . }}-config
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
data:
  DISCOURSE_ENABLE_HTTPS: "true"
  DISCOURSE_EXTERNAL_HTTP_PORT_NUMBER: "443"
  DISCOURSE_SKIP_INSTALL: "no"
