apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "discourse.fullname" . }}-discourse-data
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: discourse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.discourseData.storageSize }}
