apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discourse.fullname" . }}-secret
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCOURSE_DATABASE_HOST: {{ include "discourse.fullname" . }}-postgresql
  DISCOURSE_DATABASE_PORT_NUMBER: "5432"
  DISCOURSE_DATABASE_NAME: {{ .Values.postgresql.database | quote }}
  DISCOURSE_DATABASE_USER: {{ .Values.postgresql.user | quote }}
  DISCOURSE_DATABASE_PASSWORD: {{ .Values.postgresql.password | quote }}
  DISCOURSE_REDIS_HOST: {{ include "discourse.fullname" . }}-redis
  DISCOURSE_REDIS_PORT_NUMBER: "6379"
  DISCOURSE_HOST: {{ .Values.ingress.domain | quote }}
  DISCOURSE_SITE_NAME: {{ .Values.discourse.siteName | quote }}
  DISCOURSE_EMAIL: {{ .Values.discourse.adminEmail | quote }}
  DISCOURSE_PASSWORD: {{ .Values.discourse.adminPassword | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  {{- if .Values.smtp.host }}
  DISCOURSE_SMTP_HOST: {{ .Values.smtp.host | quote }}
  DISCOURSE_SMTP_PORT_NUMBER: {{ .Values.smtp.port | quote }}
  DISCOURSE_SMTP_USER: {{ .Values.smtp.username | quote }}
  DISCOURSE_SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  DISCOURSE_SMTP_PROTOCOL: "tls"
  {{- end }}
