apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.fullname" . }}
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: discourse
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: discourse
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.fullname" . }}-postgresql
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "discourse.fullname" . }}-redis
  labels:
    {{- include "discourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "discourse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
