replicaCount: 1

image:
  repository: minio/minio
  tag: "RELEASE.2025-02-28T09-55-16Z"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

resources:
  requests:
    cpu: 0.25
    memory: 256Mi
  limits:
    cpu: 0.25
    memory: 256Mi

persistence:
  enabled: true
  mountPath: "/data"
  size: 20Gi

auth:
  rootUser: ""
  rootPassword: ""
