bookstack:
  image: "lscr.io/linuxserver/bookstack:latest"
  replicas: 1
  appUrl: ""
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

mariadb:
  image: mariadb:10.11
  rootPassword: ""
  database: bookstack
  user: bookstack
  password: ""
  storageSize: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations: {}

bookstackData:
  storageSize: 2Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
