apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitea.fullname" . }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    app.kubernetes.io/component: gitea
spec:
  replicas: {{ .Values.gitea.replicas }}
  selector:
    matchLabels:
      {{- include "gitea.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gitea
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "gitea.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gitea
    spec:
      containers:
        - name: gitea
          image: {{ .Values.gitea.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            - name: ssh
              containerPort: 22
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "gitea.fullname" . }}-secret
          env:
            - name: GITEA__database__DB_TYPE
              value: "postgres"
            - name: GITEA__database__HOST
              value: "{{ include "gitea.fullname" . }}-postgresql:5432"
            - name: GITEA__database__NAME
              value: {{ .Values.postgresql.database | quote }}
            - name: GITEA__database__USER
              value: {{ .Values.postgresql.user | quote }}
            - name: GITEA__server__SSH_DOMAIN
              value: {{ .Values.ingress.domain | quote }}
            - name: GITEA__server__DOMAIN
              value: {{ .Values.ingress.domain | quote }}
            - name: GITEA__server__ROOT_URL
              value: "https://{{ .Values.ingress.domain }}"
            - name: GITEA__server__SSH_PORT
              value: "22"
            - name: GITEA__server__LFS_START_SERVER
              value: {{ .Values.gitea.lfsEnabled | quote }}
          volumeMounts:
            - name: gitea-data
              mountPath: /data
          resources:
            requests:
              cpu: {{ .Values.gitea.resources.requests.cpu }}
              memory: {{ .Values.gitea.resources.requests.memory }}
            limits:
              cpu: {{ .Values.gitea.resources.limits.cpu }}
              memory: {{ .Values.gitea.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: false
      volumes:
        - name: gitea-data
          persistentVolumeClaim:
            claimName: {{ include "gitea.fullname" . }}-data
