apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gitea.fullname" . }}-gitea
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gitea.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gitea
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 3000
          protocol: TCP
        - port: 22
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gitea.fullname" . }}-postgresql
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gitea.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "gitea.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: gitea
      ports:
        - port: 5432
          protocol: TCP
