apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitea.fullname" . }}-data
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
    app.kubernetes.io/component: gitea
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.giteaData.storageSize }}
