apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-secret
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  GITEA__database__PASSWD: {{ .Values.postgresql.password | quote }}
  GITEA_ADMIN_USERNAME: {{ .Values.gitea.adminUser | quote }}
  GITEA_ADMIN_PASSWORD: {{ .Values.gitea.adminPassword | quote }}
  GITEA_ADMIN_EMAIL: {{ .Values.gitea.adminEmail | quote }}
  {{- if .Values.smtp.host }}
  GITEA__mailer__ENABLED: "true"
  GITEA__mailer__SMTP_ADDR: {{ .Values.smtp.host | quote }}
  GITEA__mailer__SMTP_PORT: {{ .Values.smtp.port | quote }}
  GITEA__mailer__USER: {{ .Values.smtp.username | quote }}
  GITEA__mailer__PASSWD: {{ .Values.smtp.password | quote }}
  {{- end }}
