apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rocketchat.fullname" . }}-config
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
data:
  PORT: "3000"
  DEPLOY_METHOD: "helm"
  DEPLOY_PLATFORM: "kubernetes"
  OVERWRITE_SETTING_Show_Setup_Wizard: "completed"
