apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rocketchat.fullname" . }}-rocketchat
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rocketchat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rocketchat
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 3000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rocketchat.fullname" . }}-mongodb
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "rocketchat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "rocketchat.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: rocketchat
      ports:
        - port: 27017
          protocol: TCP
