apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rocketchat.fullname" . }}-rc-uploads
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: rocketchat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.rcUploads.storageSize }}
