apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketchat.fullname" . }}-secret
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URL: "mongodb://{{ include "rocketchat.fullname" . }}-mongodb:27017/{{ .Values.mongodb.database }}?replicaSet=rs0"
  MONGO_OPLOG_URL: "mongodb://{{ include "rocketchat.fullname" . }}-mongodb:27017/local?replicaSet=rs0"
  ROOT_URL: "https://{{ .Values.ingress.domain }}"
  ADMIN_USERNAME: {{ .Values.rocketchat.adminUser | quote }}
  ADMIN_PASS: {{ .Values.rocketchat.adminPassword | quote }}
  ADMIN_EMAIL: {{ .Values.rocketchat.adminEmail | quote }}
  {{- if .Values.smtp.host }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  OVERWRITE_SETTING_SMTP_Host: {{ .Values.smtp.host | quote }}
  OVERWRITE_SETTING_SMTP_Port: {{ .Values.smtp.port | quote }}
  OVERWRITE_SETTING_SMTP_Username: {{ .Values.smtp.username | quote }}
  OVERWRITE_SETTING_SMTP_Password: {{ .Values.smtp.password | quote }}
  {{- end }}
