apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dolibarr.fullname" . }}
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: dolibarr
spec:
  replicas: {{ .Values.dolibarr.replicas }}
  selector:
    matchLabels:
      {{- include "dolibarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dolibarr
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "dolibarr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dolibarr
    spec:
      containers:
        - name: dolibarr
          image: {{ .Values.dolibarr.image }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "dolibarr.fullname" . }}-secret
          env:
            - name: DOLI_URL_ROOT
              value: "https://{{ .Values.ingress.domain }}"
            - name: DOLI_MODULES
              value: {{ .Values.dolibarr.modules | quote }}
            - name: PHP_INI_UPLOAD_MAX_FILESIZE
              value: {{ .Values.dolibarr.uploadMaxSize | quote }}
            - name: PHP_INI_POST_MAX_SIZE
              value: {{ .Values.dolibarr.uploadMaxSize | quote }}
            - name: PHP_INI_MEMORY_LIMIT
              value: {{ .Values.dolibarr.phpMemoryLimit | quote }}
            - name: PHP_INI_DATE_TIMEZONE
              value: {{ .Values.dolibarr.timezone | quote }}
          volumeMounts:
            - name: documents
              mountPath: /var/www/html/documents
            - name: custom
              mountPath: /var/www/html/custom
          resources:
            requests:
              cpu: {{ .Values.dolibarr.resources.requests.cpu }}
              memory: {{ .Values.dolibarr.resources.requests.memory }}
            limits:
              cpu: {{ .Values.dolibarr.resources.limits.cpu }}
              memory: {{ .Values.dolibarr.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /index.php
              port: http
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /index.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: false
      volumes:
        - name: documents
          persistentVolumeClaim:
            claimName: {{ include "dolibarr.fullname" . }}-documents
        - name: custom
          persistentVolumeClaim:
            claimName: {{ include "dolibarr.fullname" . }}-custom
