apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dolibarr.fullname" . }}-dolibarr
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dolibarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dolibarr
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 80
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "dolibarr.fullname" . }}-mariadb
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "dolibarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "dolibarr.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: dolibarr
      ports:
        - port: 3306
          protocol: TCP
