apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dolibarr.fullname" . }}-documents
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: dolibarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dolibarr.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dolibarr.fullname" . }}-custom
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: dolibarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dolibarrCustom.storageSize }}
