apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dolibarr.fullname" . }}-secret
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  DOLI_DB_HOST: {{ include "dolibarr.fullname" . }}-mariadb
  DOLI_DB_HOST_PORT: "3306"
  DOLI_DB_NAME: {{ .Values.mariadb.database | quote }}
  DOLI_DB_USER: {{ .Values.mariadb.user | quote }}
  DOLI_DB_PASSWORD: {{ .Values.mariadb.password | quote }}
  DOLI_ADMIN_LOGIN: {{ .Values.dolibarr.adminLogin | quote }}
  DOLI_ADMIN_PASSWORD: {{ .Values.dolibarr.adminPassword | quote }}
  {{- if .Values.smtp.host }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  {{- end }}
