apiVersion: v1
kind: Service
metadata:
  name: {{ include "dolibarr.fullname" . }}
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: dolibarr
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dolibarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dolibarr
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dolibarr.fullname" . }}-mariadb
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "dolibarr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
