replicaCount: 1

image:
  repository: ghcr.io/phoenixtechnam/k8s-application-catalog/apache-php84
  tag: "8.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  domain: ""
  tls: true

resources:
  requests:
    cpu: 0.25
    memory: 256Mi
  limits:
    cpu: 0.25
    memory: 256Mi

persistence:
  enabled: true
  mountPath: "/var/www/html"
  size: 5Gi

env: {}
