apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "plausible.fullname" . }}-plausible
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "plausible.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: plausible
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 8000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "plausible.fullname" . }}-postgresql
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "plausible.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "plausible.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: plausible
      ports:
        - port: 5432
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "plausible.fullname" . }}-clickhouse
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "plausible.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: clickhouse
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "plausible.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: plausible
      ports:
        - port: 8123
          protocol: TCP
