apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plausible.fullname" . }}-secret
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_USER_EMAIL: {{ .Values.plausible.adminEmail | quote }}
  ADMIN_USER_PWD: {{ .Values.plausible.adminPassword | quote }}
  SECRET_KEY_BASE: {{ .Values.plausible.secretKeyBase | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  {{- if .Values.smtp.host }}
  MAILER_ADAPTER: "Bamboo.SMTPAdapter"
  SMTP_HOST_ADDR: {{ .Values.smtp.host | quote }}
  SMTP_HOST_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USER_NAME: {{ .Values.smtp.username | quote }}
  SMTP_USER_PWD: {{ .Values.smtp.password | quote }}
  {{- end }}
