apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plausible.fullname" . }}-clickhouse
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  serviceName: {{ include "plausible.fullname" . }}-clickhouse
  replicas: 1
  selector:
    matchLabels:
      {{- include "plausible.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: clickhouse
  template:
    metadata:
      labels:
        {{- include "plausible.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: {{ .Values.clickhouse.image }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.clickhouse.resources.requests.cpu }}
              memory: {{ .Values.clickhouse.resources.requests.memory }}
            limits:
              cpu: {{ .Values.clickhouse.resources.limits.cpu }}
              memory: {{ .Values.clickhouse.resources.limits.memory }}
          volumeMounts:
            - name: ch-data
              mountPath: /var/lib/clickhouse
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: ch-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.clickhouse.storageSize }}
