rocketchat:
  image: rocket.chat:7
  replicas: 1
  adminUser: "admin"
  adminPassword: ""
  adminEmail: ""
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

mongodb:
  image: mongo:7
  database: rocketchat
  oplogSizeMB: 128
  storageSize: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

rcUploads:
  storageSize: 10Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
