uptimeKuma:
  image: "louislam/uptime-kuma:1"
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations: {}

kumaData:
  storageSize: 1Gi
