apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiki-js.fullname" . }}-wiki
  labels:
    {{- include "wiki-js.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wiki-js.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: wiki
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 3000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wiki-js.fullname" . }}-postgresql
  labels:
    {{- include "wiki-js.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wiki-js.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "wiki-js.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: wiki
      ports:
        - port: 5432
          protocol: TCP
