apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiki-js.fullname" . }}-secret
  labels:
    {{- include "wiki-js.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASS: {{ .Values.postgresql.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  WIKI_ADMIN_EMAIL: {{ .Values.wiki.adminEmail | quote }}
  WIKI_ADMIN_PASSWORD: {{ .Values.wiki.adminPassword | quote }}
