apiVersion: v2
name: directus
description: Directus - Open-source data platform with REST and GraphQL API
type: application
version: 1.0.0
appVersion: "11"
keywords:
  - cms
  - headless
  - directus
  - api
  - dashboard
home: https://directus.io
sources:
  - https://github.com/directus/directus
