apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextcloud.fullname" . }}-config
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
data:
  php-custom.ini: |
    memory_limit = 512M
    upload_max_filesize = 16G
    post_max_size = 16G
    max_execution_time = 3600
    max_input_time = 3600
    max_input_vars = 5000
    output_buffering = 0

    ; OPcache settings
    opcache.enable = 1
    opcache.memory_consumption = 128
    opcache.max_accelerated_files = 10000
    opcache.revalidate_freq = 60
    opcache.interned_strings_buffer = 16
    opcache.save_comments = 1
    opcache.jit = 1255
    opcache.jit_buffer_size = 128M

  apache-custom.conf: |
    <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
      Header always set Referrer-Policy "no-referrer"
      Header always set X-Content-Type-Options "nosniff"
      Header always set X-Frame-Options "SAMEORIGIN"
      Header always set X-Permitted-Cross-Domain-Policies "none"
      Header always set X-Robots-Tag "noindex, nofollow"
      Header always set X-XSS-Protection "1; mode=block"
    </IfModule>

    <IfModule mod_reqtimeout.c>
      RequestReadTimeout header=20-40,MinRate=500 body=20,MinRate=500
    </IfModule>

  NEXTCLOUD_DEFAULT_PHONE_REGION: {{ .Values.nextcloud.defaultPhoneRegion | quote }}
