apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "nextcloud.fullname" . }}-cron
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: cron
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "nextcloud.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cron
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cron
              image: {{ .Values.nextcloud.image }}
              command:
                - php
                - -f
                - /var/www/html/cron.php
              volumeMounts:
                - name: nextcloud-data
                  mountPath: /var/www/html/data
                - name: nextcloud-config
                  mountPath: /var/www/html/config
                - name: nextcloud-custom-apps
                  mountPath: /var/www/html/custom_apps
              resources:
                {{- toYaml .Values.cron.resources | nindent 16 }}
          volumes:
            - name: nextcloud-data
              persistentVolumeClaim:
                claimName: {{ include "nextcloud.fullname" . }}-data
            - name: nextcloud-config
              persistentVolumeClaim:
                claimName: {{ include "nextcloud.fullname" . }}-config
            - name: nextcloud-custom-apps
              persistentVolumeClaim:
                claimName: {{ include "nextcloud.fullname" . }}-custom-apps
