{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextcloud.fullname" . }}
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/server-snippet: |
      server_tokens off;
      proxy_hide_header X-Powered-By;
      rewrite ^/.well-known/carddav https://$server_name/remote.php/dav/ redirect;
      rewrite ^/.well-known/caldav https://$server_name/remote.php/dav/ redirect;
      rewrite ^/.well-known/webfinger https://$server_name/index.php/.well-known/webfinger redirect;
      rewrite ^/.well-known/nodeinfo https://$server_name/index.php/.well-known/nodeinfo redirect;
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=15552000; includeSubDomains; preload";
    {{- if or .Values.collabora.enabled }}
    nginx.ingress.kubernetes.io/proxy-set-headers: "Upgrade $http_upgrade; Connection upgrade"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain | quote }}
      secretName: {{ include "nextcloud.fullname" . }}-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextcloud.fullname" . }}
                port:
                  number: 80
{{- if .Values.collabora.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextcloud.fullname" . }}-collabora
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=15552000; includeSubDomains; preload";
    nginx.ingress.kubernetes.io/proxy-set-headers: "Upgrade $http_upgrade; Connection upgrade"
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.collabora.domain | default (printf "office.%s" .Values.ingress.domain) | quote }}
      secretName: {{ include "nextcloud.fullname" . }}-collabora-tls
  {{- end }}
  rules:
    - host: {{ .Values.collabora.domain | default (printf "office.%s" .Values.ingress.domain) | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextcloud.fullname" . }}-collabora
                port:
                  number: 9980
{{- end }}
{{- end }}
