apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud.fullname" . }}-secret
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  MYSQL_HOST: {{ include "nextcloud.fullname" . }}-mariadb
  MYSQL_DATABASE: {{ .Values.mariadb.database | quote }}
  MYSQL_USER: {{ .Values.mariadb.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.password | quote }}
  NEXTCLOUD_ADMIN_USER: {{ .Values.nextcloud.adminUser | quote }}
  NEXTCLOUD_ADMIN_PASSWORD: {{ .Values.nextcloud.adminPassword | quote }}
  NEXTCLOUD_TRUSTED_DOMAINS: {{ .Values.nextcloud.trustedDomains | quote }}
  {{- if .Values.redis.enabled }}
  REDIS_HOST: {{ include "nextcloud.fullname" . }}-redis
  {{- if .Values.redis.password }}
  REDIS_HOST_PASSWORD: {{ .Values.redis.password | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.nextcloud.smtpHost }}
  SMTP_HOST: {{ .Values.nextcloud.smtpHost | quote }}
  SMTP_PORT: {{ .Values.nextcloud.smtpPort | quote }}
  SMTP_NAME: {{ .Values.nextcloud.smtpUser | quote }}
  SMTP_PASSWORD: {{ .Values.nextcloud.smtpPassword | quote }}
  MAIL_FROM_ADDRESS: {{ .Values.nextcloud.smtpFromAddress | quote }}
  SMTP_SECURE: "tls"
  SMTP_AUTHTYPE: "LOGIN"
  {{- end }}
