n8n:
  image: "n8nio/n8n:latest"
  replicas: 1
  webhookUrl: ""
  basicAuthUser: ""
  basicAuthPassword: ""
  encryptionKey: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

postgresql:
  image: postgres:16-alpine
  database: n8n
  user: n8n
  password: ""
  storageSize: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations: {}

n8nData:
  storageSize: 5Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
