apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-data
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-media
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  {{- if .Values.persistence.media.storageClass }}
  storageClassName: {{ .Values.persistence.media.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-consume
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
spec:
  accessModes:
    - {{ .Values.persistence.consume.accessMode }}
  {{- if .Values.persistence.consume.storageClass }}
  storageClassName: {{ .Values.persistence.consume.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.consume.size }}
