apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-secret
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  secret-key: {{ .Values.app.secretKey | quote }}
  admin-password: {{ .Values.admin.password | quote }}
  {{- if .Values.smtp.password }}
  smtp-password: {{ .Values.smtp.password | quote }}
  {{- end }}
