apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-app
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.paperless.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ngx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: paperless
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-postgresql
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "paperless-ngx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "paperless-ngx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
