apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich.fullname" . }}-ml
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: immich-ml
spec:
  replicas: {{ .Values.immichMl.replicas }}
  selector:
    matchLabels:
      {{- include "immich.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: immich-ml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "immich.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: immich-ml
    spec:
      containers:
        - name: immich-ml
          image: {{ .Values.immichMl.image }}
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          volumeMounts:
            - name: ml-cache
              mountPath: /cache
          resources:
            requests:
              cpu: {{ .Values.immichMl.resources.requests.cpu }}
              memory: {{ .Values.immichMl.resources.requests.memory }}
            limits:
              cpu: {{ .Values.immichMl.resources.limits.cpu }}
              memory: {{ .Values.immichMl.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: ml-cache
          persistentVolumeClaim:
            claimName: {{ include "immich.fullname" . }}-ml-cache
