apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-upload-data
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: immich-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.uploadData.storageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-ml-cache
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: immich-ml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mlCache.storageSize }}
