apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-secret
  labels:
    {{- include "immich.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOSTNAME: {{ include "immich.fullname" . }}-postgresql
  DB_PORT: "5432"
  DB_DATABASE_NAME: {{ .Values.postgresql.database | quote }}
  DB_USERNAME: {{ .Values.postgresql.user | quote }}
  DB_PASSWORD: {{ .Values.postgresql.password | quote }}
  REDIS_HOSTNAME: {{ include "immich.fullname" . }}-redis
  REDIS_PORT: "6379"
  IMMICH_MACHINE_LEARNING_URL: {{ .Values.immichMl.url | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
