apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-server
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: immich-server
spec:
  type: ClusterIP
  ports:
    - port: 2283
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: immich-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-ml
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: immich-ml
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: immich-ml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-postgresql
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich.fullname" . }}-redis
  labels:
    {{- include "immich.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "immich.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
