apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "coturn.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 3478
          protocol: TCP
        - port: 3478
          protocol: UDP
        {{- if .Values.coturn.tlsEnabled }}
        - port: 5349
          protocol: TCP
        {{- end }}
        {{- $minPort := int .Values.coturn.minPort }}
        {{- $maxPort := int .Values.coturn.maxPort }}
        {{- range untilStep $minPort (add1 $maxPort | int) 1 }}
        - port: {{ . }}
          protocol: UDP
        {{- end }}
