apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}
  labels:
    {{- include "coturn.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3478
      targetPort: turn-tcp
      protocol: TCP
      name: turn-tcp
    - port: 3478
      targetPort: turn-udp
      protocol: UDP
      name: turn-udp
  selector:
    {{- include "coturn.selectorLabels" . | nindent 4 }}
