gitea:
  image: gitea/gitea:1.22
  replicas: 1
  adminUser: "gitea_admin"
  adminPassword: ""
  adminEmail: ""
  sshEnabled: true
  lfsEnabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

postgresql:
  image: postgres:16-alpine
  database: gitea
  user: gitea
  password: ""
  storageSize: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations: {}

giteaData:
  storageSize: 10Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
