matomo:
  image: matomo:5
  replicas: 1
  adminUser: "admin"
  adminPassword: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

mariadb:
  image: mariadb:10.11
  rootPassword: ""
  database: matomo
  user: matomo_user
  password: ""
  storageSize: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"

matomoData:
  storageSize: 5Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
