apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "directus.fullname" . }}-uploads
  labels:
    {{- include "directus.labels" . | nindent 4 }}
    app.kubernetes.io/component: directus
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  {{- if .Values.persistence.uploads.storageClass }}
  storageClassName: {{ .Values.persistence.uploads.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "directus.fullname" . }}-extensions
  labels:
    {{- include "directus.labels" . | nindent 4 }}
    app.kubernetes.io/component: directus
spec:
  accessModes:
    - {{ .Values.persistence.extensions.accessMode }}
  {{- if .Values.persistence.extensions.storageClass }}
  storageClassName: {{ .Values.persistence.extensions.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.extensions.size }}
