apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus.fullname" . }}-secret
  labels:
    {{- include "directus.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  app-secret: {{ .Values.app.secret | quote }}
  admin-password: {{ .Values.admin.password | quote }}
