apiVersion: v1
kind: Service
metadata:
  name: {{ include "directus.fullname" . }}-app
  labels:
    {{- include "directus.labels" . | nindent 4 }}
    app.kubernetes.io/component: directus
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.directus.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "directus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: directus
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "directus.fullname" . }}-postgresql
  labels:
    {{- include "directus.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "directus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
