apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "directus.fullname" . }}-postgresql
  labels:
    {{- include "directus.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "directus.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "directus.fullname" . }}-secret
                  key: db-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.db.user | quote }}
                - -d
                - {{ .Values.db.name | quote }}
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.db.user | quote }}
                - -d
                - {{ .Values.db.name | quote }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.postgresql.resources.requests.cpu }}
              memory: {{ .Values.postgresql.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgresql.resources.limits.cpu }}
              memory: {{ .Values.postgresql.resources.limits.memory }}
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes:
          - {{ .Values.persistence.dbData.accessMode }}
        {{- if .Values.persistence.dbData.storageClass }}
        storageClassName: {{ .Values.persistence.dbData.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.dbData.size }}
