# Invoice Ninja values
domain: ""

invoiceninja:
  image:
    repository: invoiceninja/invoiceninja
    tag: "5"
    pullPolicy: IfNotPresent
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

app:
  url: ""
  key: ""

admin:
  email: ""
  password: ""

smtp:
  host: ""
  port: 587
  username: ""
  password: ""

db:
  name: invoiceninja
  user: invoiceninja
  password: ""

mariadb:
  image:
    repository: mariadb
    tag: "10.11"
    pullPolicy: IfNotPresent
  port: 3306
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

persistence:
  public:
    size: 5Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  storage:
    size: 5Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  dbData:
    size: 5Gi
    storageClass: ""
    accessMode: ReadWriteOnce

ingress:
  enabled: true
  className: nginx
  annotations: {}
  tls:
    enabled: true
    secretName: ""

networkPolicy:
  enabled: true
