apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bookstack.fullname" . }}-data
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
    app.kubernetes.io/component: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bookstackData.storageSize }}
