apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookstack.fullname" . }}-secret
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MARIADB_DATABASE: {{ .Values.mariadb.database | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | quote }}
  DB_PASSWORD: {{ .Values.mariadb.password | quote }}
  {{- if .Values.smtp.host }}
  MAIL_DRIVER: "smtp"
  MAIL_HOST: {{ .Values.smtp.host | quote }}
  MAIL_PORT: {{ .Values.smtp.port | quote }}
  MAIL_USERNAME: {{ .Values.smtp.username | quote }}
  MAIL_PASSWORD: {{ .Values.smtp.password | quote }}
  MAIL_ENCRYPTION: "tls"
  {{- end }}
