vaultwarden:
  image: vaultwarden/server:latest
  replicas: 1
  signupsAllowed: false
  adminToken: ""
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

ingress:
  enabled: true
  domain: ""
  tls: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"

vwData:
  storageSize: 1Gi

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
