apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi.fullname" . }}-env
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
data:
  XMPP_DOMAIN: {{ .Values.ingress.domain | quote }}
  XMPP_SERVER: {{ include "jitsi.prosody.fullname" . | quote }}
  XMPP_BOSH_URL_BASE: "http://{{ include "jitsi.prosody.fullname" . }}:5280/http-bind"
  XMPP_MUC_DOMAIN: "muc.{{ .Values.ingress.domain }}"
  XMPP_AUTH_DOMAIN: "auth.{{ .Values.ingress.domain }}"
  XMPP_INTERNAL_MUC_DOMAIN: "internal-muc.{{ .Values.ingress.domain }}"
  XMPP_GUEST_DOMAIN: "guest.{{ .Values.ingress.domain }}"
  JVB_BREWERY_MUC: "jvbbrewery"
  JVB_PORT: "10000"
  JVB_STUN_SERVERS: "meet-jit-si-turnrelay.jitsi.net:443"
  JICOFO_AUTH_USER: "focus"
  JVB_AUTH_USER: "jvb"
  ENABLE_LOBBY: {{ .Values.jitsi.enableLobby | quote }}
  DEFAULT_LANGUAGE: {{ .Values.jitsi.defaultLanguage | quote }}
  AUTH_TYPE: {{ .Values.jitsi.authType | quote }}
  ENABLE_GUESTS: {{ .Values.jitsi.enableGuests | quote }}
  {{- if .Values.jitsi.enableRecording }}
  ENABLE_RECORDING: "1"
  {{- end }}
