apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jitsi.jvb.fullname" . }}
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: jvb
spec:
  replicas: {{ .Values.jvb.replicas }}
  selector:
    matchLabels:
      {{- include "jitsi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: jvb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "jitsi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: jvb
    spec:
      containers:
        - name: jvb
          image: {{ .Values.jvb.image }}
          ports:
            - name: media
              containerPort: 10000
              protocol: UDP
              hostPort: {{ .Values.jvb.hostPort }}
            - name: colibri
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "jitsi.fullname" . }}-env
            - secretRef:
                name: {{ include "jitsi.fullname" . }}-secret
          env:
            - name: JVB_ADVERTISE_IPS
              value: {{ .Values.jvb.publicIP | quote }}
            - name: COLIBRI_WEBSOCKET_ENABLED
              value: {{ .Values.jvb.enableWsColibri | quote }}
          resources:
            requests:
              cpu: {{ .Values.jvb.resources.requests.cpu }}
              memory: {{ .Values.jvb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.jvb.resources.limits.cpu }}
              memory: {{ .Values.jvb.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /about/health
              port: colibri
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /about/health
              port: colibri
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
