apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jitsi.fullname" . }}-prosody-config
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: prosody
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
