apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jitsi.fullname" . }}-secret
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
type: Opaque
stringData:
  JICOFO_AUTH_PASSWORD: {{ .Values.jicofo.componentSecret | default (randAlphaNum 32) | quote }}
  JICOFO_COMPONENT_SECRET: {{ .Values.jicofo.componentSecret | default (randAlphaNum 32) | quote }}
  JVB_AUTH_PASSWORD: {{ randAlphaNum 32 | quote }}
  {{- if .Values.coturn.enabled }}
  TURN_CREDENTIALS: {{ .Values.coturn.authSecret | quote }}
  {{- end }}
