apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.web.fullname" . }}
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jitsi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.prosody.fullname" . }}
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: prosody
spec:
  type: ClusterIP
  ports:
    - port: 5222
      targetPort: xmpp-c2s
      protocol: TCP
      name: xmpp-c2s
    - port: 5280
      targetPort: xmpp-http
      protocol: TCP
      name: xmpp-http
  selector:
    {{- include "jitsi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prosody
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.jvb.fullname" . }}
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: jvb
spec:
  type: ClusterIP
  ports:
    - port: 10000
      targetPort: media
      protocol: UDP
      name: media
  selector:
    {{- include "jitsi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: jvb
{{- if .Values.coturn.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi.coturn.fullname" . }}
  labels:
    {{- include "jitsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: coturn
spec:
  type: ClusterIP
  ports:
    - port: 3478
      targetPort: stun-udp
      protocol: UDP
      name: stun-udp
    - port: 3478
      targetPort: stun-tcp
      protocol: TCP
      name: stun-tcp
  selector:
    {{- include "jitsi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coturn
{{- end }}
