apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prestashop.fullname" . }}
  labels:
    {{- include "prestashop.labels" . | nindent 4 }}
    app.kubernetes.io/component: prestashop
spec:
  replicas: {{ .Values.prestashop.replicas }}
  selector:
    matchLabels:
      {{- include "prestashop.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prestashop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "prestashop.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prestashop
    spec:
      containers:
        - name: prestashop
          image: {{ .Values.prestashop.image }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "prestashop.fullname" . }}-secret
          env:
            - name: PS_DOMAIN
              value: {{ .Values.ingress.domain | quote }}
            - name: PS_LANGUAGE
              value: {{ .Values.prestashop.language | quote }}
            - name: PS_FOLDER_ADMIN
              value: "admin"
            - name: PS_INSTALL_AUTO
              value: "1"
            - name: PS_ERASE_DB
              value: "0"
          volumeMounts:
            - name: ps-data
              mountPath: /var/www/html
          resources:
            requests:
              cpu: {{ .Values.prestashop.resources.requests.cpu }}
              memory: {{ .Values.prestashop.resources.requests.memory }}
            limits:
              cpu: {{ .Values.prestashop.resources.limits.cpu }}
              memory: {{ .Values.prestashop.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /index.php
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /index.php
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          securityContext:
            runAsNonRoot: false
      volumes:
        - name: ps-data
          persistentVolumeClaim:
            claimName: {{ include "prestashop.fullname" . }}-ps-data
