coturn:
  image: coturn/coturn:4.6
  realm: ""
  authSecret: ""
  publicIP: ""
  minPort: 49152
  maxPort: 49200
  tlsEnabled: false
  maxBandwidth: 10000000

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
