apiVersion: v1
kind: Secret
metadata:
  name: {{ include "invoiceninja.fullname" . }}-secret
  labels:
    {{- include "invoiceninja.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.db.password | quote }}
  app-key: {{ .Values.app.key | quote }}
  admin-password: {{ .Values.admin.password | quote }}
  {{- if .Values.smtp.password }}
  smtp-password: {{ .Values.smtp.password | quote }}
  {{- end }}
