apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoiceninja.fullname" . }}-app
  labels:
    {{- include "invoiceninja.labels" . | nindent 4 }}
    app.kubernetes.io/component: invoiceninja
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.invoiceninja.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "invoiceninja.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: invoiceninja
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invoiceninja.fullname" . }}-mariadb
  labels:
    {{- include "invoiceninja.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mariadb.port }}
      targetPort: mariadb
      protocol: TCP
      name: mariadb
  selector:
    {{- include "invoiceninja.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
