apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.auth.database | quote }}
  MYSQL_USER: {{ .Values.auth.username | quote }}
  MYSQL_PASSWORD: {{ .Values.auth.password | quote }}
